### ISSUE TITLE
MyStyle file name has a casing typo

### ISSUE THREAD

**Issue by andys8** [lucamug/style-framework#1]
Hey,

we're using https://github.com/andys8/elm-compiler-test to find packages that could potentially not work when Elm 0.19.1 is released. 

There is a difference in the module `MyStyle` and the filename `myStyle.elm`. It's first letter has to be uppercased  :)

I'm not sure if this is an issue with 0.19.0, too, because it'll only relevant for Linux users. Windows and Mac are case insensitive.

```
-- MODULE NOT FOUND ---------------------------- src/Framework/Configuration.elm

You are trying to import a `MyStyle` module:

21| import MyStyle
           ^^^^^^^
I checked the "dependencies" and "source-directories" listend in your elm.json,
but I cannot find it! Maybe it is a typo for one of these names?

    Html
    Array
    Bitwise
    Set

Hint: If it is not a typo, check the "dependencies" and "source-directories" of
your elm.json to make sure all the packages you need are listed there!
```

**Comment by lucamug** [comment]
I renamed `myStyle.elm` to `MyStyle.elm` in version `1.0.1`
